### ISSUE TITLE
V1 - Phase 1 plan

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/SatisfactoryPlanning#18]
# Phase 1

**Goal:** Establish our base location and automate all phase 1 production. Start in a spot with plenty of iron, and copper and limestone - all as close as possible! (at the beginning you have a lot of walking - it's easier to build a base close to these). Start to think about where the mall and space elevator will be - looking ahead to the future where we want to setup our base of operations. We also want to focus on getting to research tier 3 as quickly as possible to tap into coal power. With Coal power we can stop manually feeding the biomass burners, relax a little with the wood and leaf collection, and really start to focus on a robust infrastructure. 

- [x] Choose your production/building color palate!
- [x] Setup new todos for this phase in game
- [x] Find 200 Iron, 45 Copper, and 90 Limestone, and implement this [plan](https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_Cement_C%22%3A%2230%22%2C%22Desc_IronRod_C%22%3A%225%22%2C%22Desc_IronPlate_C%22%3A%2210%22%2C%22Desc_IronPlateReinforced_C%22%3A%227%22%2C%22Desc_ModularFrame_C%22%3A%222%22%2C%22Desc_Rotor_C%22%3A%224%22%2C%22Desc_Wire_C%22%3A%2230%22%2C%22Desc_Cable_C%22%3A%2230%22%2C%22Desc_Biofuel_C%22%3A%224%22%7D):
  ![Image](https://github.com/user-attachments/assets/a6340c5c-c404-447e-bedd-881449fabe4e)
- [x] We require 240MW power (8 biomass generators at 30MW each). The image below is trying to show the progression. Recommendation is two storage containers, one for wood, one for leaves, that each feed into their corresponding constructors for biomass - that then merges into a 3rd constructor to make the solid biofuel. ![image](https://github.com/samsmithnz/SatisfactoryPlanning/assets/8389039/976300df-5003-4fa6-bf30-77a18302a72f) 
- [x] Complete research in this priority order
  - [x] Logistics
  - [x] Base Building
  - [ ] Obstacle Clearing
  - [x] Part Assembly 
  - [x] Logistics Mk2
  - [x] Complete the other research items (Field Research, Jump Pads, Sink), as able. 
- [x] Build the space elevator, and a separate production line for smart plating
  - [x] Initial system of imports and exports for the space elevator starts very simple - just exporting 2 iron products to the space elevator. ![Image](https://github.com/user-attachments/assets/6be91b60-43d6-4c5e-a93f-72b0756ba4a4)
  - [x] As we start to plan for our four Space Elevator factories, in the design below we need a large flat space with plenty of space for 4 factories to be build North, East, South, and West. As we get through each phase of the elevator, we build a new factory on top - with supporting train stations for each wing and level. 
  ![Image](https://github.com/user-attachments/assets/129f92d1-b009-4f1c-9b69-3abd96f396b2)
  - [x] Space elevator parts [Plan](https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_SpaceElevatorPart_1_C%22%3A%222%22%2C%22input%22%3A%7B%22Desc_IronPlateReinforced_C%22%3A%222%22%2C%22Desc_Rotor_C%22%3A%222%22%7D%7D)
    ![Image](https://github.com/users/samsmithnz/projects/7/assets/8389039/41df91fd-245b-4520-ad49-098b261e9ccb)
- [x] Start to plan for the mall, 36 tiles long, 3-4 wide

**Comment by samsmithnz** [comment]
After phase 1 is completed: ![Image](https://github.com/user-attachments/assets/96425185-bb59-4055-a83d-0080591280e8)

**Comment by samsmithnz** [comment]
Feedback: Still not enough Reinforced Plates, Iron Platers, and Concrete. Need to find a way to either start with a bigger load or scale them up phase by phase.
